# CMSC 197 - 1 Quiz 1
## John Gabriel Cabatu-an

----


#### PART 1

In [38]:
import numpy as np

- Create 2 2D arrays, y_hat and y
- Initialize y_hat with 20 linearly spaced numbers between -1 and 1

In [39]:
y_hat = np.linspace(-1,1,num=20)
y_hat

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

- Initialize y with 20 linearly spaced numbers between 0 and 1

In [40]:
y = np.linspace(0,1,num=20)
y

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

- Compute for the shape and dimension of y_hat and y.

In [41]:
np.shape(y_hat), np.shape(y)

((20,), (20,))

In [51]:
y_hat.ndim

1

In [52]:
y.ndim

1

- Create individual functions for each of the loss functions with y and
y_hat as parameters

- Each function should return the loss value (L)

In [42]:
# Mean Squared Error
def MSE(y_hat, y):
	return np.square(y_hat-y).mean()

# Mean Absolute Error
def MAE(y_hat, y):
	return np.absolute(y_hat-y).mean()

# Mean Squared Logarithmic Error
def MSLE(y_hat, y):
	return np.square(np.log(y_hat+1) - np.log(y+1)).mean()

# Mean Absolute Percentage Error
def MAPE(y_hat, y):
	return np.absolute((y_hat-y)/y).mean()


----

#### PART 2

- Create a 1d array M {1, 2, …16} using the arange function

In [43]:
m = np.arange(1,17,1)

- Reshape M into 4x4 array and store it to N

In [44]:
n = np.reshape(m, (4,4))
n

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

- Get the 2nd row of N

In [45]:
n[1]

array([5, 6, 7, 8])

- Get the minimum values for each column of N

In [46]:
np.min(n, axis=0)

array([1, 2, 3, 4])

- Get the locations of the minimum values for each column of N

In [47]:
np.argmin(n, axis=0)

array([0, 0, 0, 0])

- Get the average of the whole matrix

In [48]:
np.average(n)

8.5

- Create a vector V with 4 elements, each element is 1

In [49]:
v = np.array([1]*4)
v

array([1, 1, 1, 1])

- Take the dot product of N and V

In [50]:
np.dot(n,v)

array([10, 26, 42, 58])